#! /bin/bash

set -eo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

cd "$DIR"

[ -d node_modules ] || npm install

npx elm-live src/Main.elm -- --debug --output=main.js
